#!/bin/sh
# Startup script for anacron
#
# chkconfig: 2345 05 92
# description: Anacron a periodic command scheduler.

# Source function library.
. /etc/rc.d/init.d/functions

[ -f /usr/sbin/anacron ] || exit 0

case "$1" in
  start)
		msg_starting "anacron" 
		daemon anacron
		;;
	
  stop)
		msg_stopping "anacron"
		killproc anacron 
		;;
	
	status)
		status anacron
		;;

	restart)
		$0 stop
		$0 start
		;;
	
  *)
		msg_Usage "$0 {start|stop|restart|status}"
		exit 1

esac

exit 0
